# Profit and Loss

In [2]:
%reload_ext autoreload
%autoreload 2

# import system modules and set local import path
import os
import sys
import numpy
from matplotlib import pyplot
from datetime import datetime
from pandas import DataFrame, read_csv

sys.path.insert(0, os.path.abspath('../../..'))

# import local modules
from lib import config
from lib.utils import extract_date_range
from lib.plots import curve, comparison, stack, periodogram, variance_agg, PlotType, mean_reversion_halflife
from lib.data import arima, adf, stats, fbm, HypothesisTestType, ou

# Config Plot Style
pyplot.style.use(config.glyfish_style)

In [24]:
data = numpy.arange(10)
csum = numpy.cumsum(data)

In [25]:
data, csum

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45]))

In [26]:
numpy.array([0 + 1, 1 + 2, 2 + 3, 3 + 4, 4 + 5, 5 + 6, 7 + 8, 8 + 9]) / 2

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 7.5, 8.5])

In [29]:
csum[2:] = csum[2:] - csum[:-2]