# Vector Autoregression (VAR) Properties

In [VAR Simulation](http://localhost:8888/lab/tree/notebooks/random_processes/var_simulation.ipynb) the VAR model was presented and simulation methods were discussed. Here the condition for stationarity is discussed and
the analytic expressions for stationary mean, variance and autocovariance are obtained. These results are compared simulations. Computation of expectations requires transformation of the
VAR model to the companion form. This is discussed in the following section.

## Companion Form of $\text{VAR}(2)$

Consider $\text{VAR}(2)$ from the previous discussion. To obtain the companion form rewrite the model by stacking the $X_t$ column vector,

$
\begin{align}
\hat{X}_t =
\begin{bmatrix}
x^1_t \\
x^2_t \\
\vdots \\
x^m_t \\
x^1_{t-1} \\
x^2_{t-1} \\
\vdots \\
x^m_{t-1} \\
\end{bmatrix}
= \begin{bmatrix}
X_t \\
X_{t-1}
\end{bmatrix}
\end{align}
\tag{1}
$

which produces a column vector of length $2m$. For the two column vectors of length $m$, $\mathcal{M}$ and $\mathcal{E}$, pad a column vector of zeros of length $m$ to obtain

$
\begin{align}
\hat{\mathcal{M}} =
\begin{bmatrix}
\mu_1 \\
\mu_2 \\
\vdots \\
\mu_m \\
0 \\
\vdots \\
0
\end{bmatrix}
= \begin{bmatrix}
\mathcal{M} \\
\mathbb{0}_m
\end{bmatrix}
\end{align}
\tag{2}
$

$
\begin{align}
\hat{\mathcal{E}}_t =
\begin{bmatrix}
\varepsilon^1_t \\
\varepsilon^2_t \\
\vdots \\
\varepsilon^m_t \\
0 \\
\vdots \\
0
\end{bmatrix}
= \begin{bmatrix}
\mathcal{E}_t \\
\mathbb{0}_m
\end{bmatrix}
\end{align}
\tag{3}
$

finally rewrite the coefficient matrix as follows,

$
\begin{align}
\hat{\Phi} =
\begin{bmatrix}
\phi^1_{11} & \phi^1_{12} & \cdots & \phi^1_{1m} & \phi^2_{11} & \phi^2_{12} & \cdots & \phi^2_{1m} \\
\phi^1_{12} & \phi^1_{22} & \cdots & \phi^1_{2m} & \phi^2_{12} & \phi^2_{22} & \cdots & \phi^2_{2m}\\
\vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \ddots & \vdots \\
\phi^1_{1m} & \phi^1_{1m} & \cdots & \phi^1_{mm} & \phi^2_{1m} & \phi^2_{1m} & \cdots & \phi^2_{mm}\\
1 & 0 & \cdots & 0 & 0 & 0 & \cdots & 0\\
0 & 1 & \cdots & 0 & 0 & 0 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & 1 & 0 & 0 & \cdots & 0\\
\end{bmatrix}
= \begin{bmatrix}
\Phi_1 & \Phi_2 \\
\mathbb{1}_m & \mathbb{0}_{mm}
\end{bmatrix}
\end{align}
\tag{4}
$

where $\mathbb{0}_{mm}$ is a square matrix of zeros with dimensions $m\times m$. Using this representation $\text{VAR}(2)$ can be rewritten as,

$
\begin{align}
\hat{X}_t = \hat{\mathcal{M}} + \hat{\Phi} X_{t-1} + \hat{\mathcal{E}}_t
\end{align}
\tag{5}
$

which has the form of $\text{VAR}(1)$. This is called the companion form of $\text{VAR}(2)$. The Moving Average (MA) form can be obtained by repeated substitution to obtain,

$
\begin{align}
\hat{X}_t = \hat{\Phi}^t \hat{X}_0 + \hat{\mathcal{M}} \sum_{i=0}^{t-1} \hat{\Phi}^i + \sum_{i=1}^t \hat{\Phi}^{t-i} \hat{\mathcal{E}}_i
\end{align}
\tag{6}
$

If the eigenvalues of $\hat{\Phi}$, denoted by $\lambda$, satisfy $\lvert\lambda\rvert < 1$ then it can be shown that,

$
\begin{align}
\sum_{i=0}^{t-1} \hat{\Phi}^i = \frac{\mathbb{1}_m - \hat{\Phi}^t}{\mathbb{1}_m - \hat{\Phi}}
\end{align}
\tag{7}
$

which is a result similar to the scalar case. It follows that the MA model is given by,

$
\begin{align}
\hat{X}_t = \hat{\Phi}^t \hat{X}_0 + \hat{\mathcal{M}} \frac{\mathbb{1}_m - \hat{\Phi}^t}{\mathbb{1}_m - \hat{\Phi}} + \sum_{i=1}^t \hat{\Phi}^{t-i} \hat{\mathcal{E}}_i
\end{align}
\tag{8}
$

## Properties of $\text{VAR}(n)$

The previous results obtained for the companion form of $\text{VAR}(2)$ can be easily extended to $\text{VAR}(n)$ to obtain,

$
\begin{align}
\hat{X_t} = 
\begin{bmatrix}
X_t \\
X_{t-1} \\
\vdots \\
X_{t-n-1}
\end{bmatrix}
\end{align}
\tag{9}
$

$
\begin{align}
\hat{\mathcal{M}} = 
\begin{bmatrix}
\mathcal{M} \\
\mathbb{0}_{(n-1)m}
\end{bmatrix}
\end{align}
\tag{10}
$

$
\begin{align}
\hat{\mathcal{E}}_t =
\begin{bmatrix}
\mathcal{E}_t \\
\mathbb{0}_{(n-1)m}
\end{bmatrix}
\end{align}
\tag{11}
$

$
\begin{align}
\hat{\Phi} = 
\begin{bmatrix}
\Phi_1 & \Phi_2 & \cdots & \Phi_{n-1} & \Phi_n\\
\mathbb{1}_m & \mathbb{0}_m & \cdots & \mathbb{0}_m & \mathbb{0}_m \\
\mathbb{0}_m & \mathbb{1}_m & \cdots & \mathbb{0}_m & \mathbb{0}_m \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
\mathbb{0}_m & \mathbb{0}_m & \cdots & \mathbb{1}_m & \mathbb{0}_m \\
\end{bmatrix}
\end{align}
\tag{12}
$

Here $\mathbb{0}_{(n-1)m}$ is a column vector of $m$ zeros repeated $(n-1)$ times, $\mathbb{1}_m$ is an identity matrix of size $m$ and $\mathbb{0}_m$ is a square matrix of zeros of size $m$. In this representation $\text{VAR}(n)$ is modeled as column vectors containing $n$ column vectors of length $m$ and the coefficient matrix is an $n\times n$ matrix of $m\times m$ matrices. It follows that the companion form is obtained,

$
\begin{align}
\hat{X}_t = \hat{\mathcal{M}} + \hat{\Phi} X_{t-1} + \hat{\mathcal{E}}_t
\end{align}
\tag{13}
$

and the moving average is given by,

$
\begin{align}
\hat{X}_t = \hat{\Phi}^t \hat{X}_0 + \hat{\mathcal{M}} \frac{\mathbb{1}_m - \hat{\Phi}^t}{\mathbb{1}_m - \hat{\Phi}} + \sum_{i=1}^t \hat{\Phi}^{t-i} \hat{\mathcal{E}}_i
\end{align}
\tag{14}
$

Recall that,

$
\begin{align}
\text{E}\left(\mathcal{E}_t \mathcal{E}_t^\prime\right) = \Omega
\end{align}
\tag{15}
$

It follows that,

$
\begin{align}
\text{E}\left(\hat{\mathcal{E}}_t \hat{\mathcal{E}}_t^\prime\right) = \hat{\Omega}
\end{align}
\tag{16}
$

where $\hat{\Omega}$ is an $n\times n$ matrix given by,

$
\begin{align}
\hat{\Omega} =
\begin{bmatrix}
\Omega & \mathbb{0}_m & \cdots & \mathbb{0}_m \\
\mathbb{0}_m & \mathbb{0}_m & \cdots & \mathbb{0}_m \\
\vdots & \ddots & & \vdots \\
\mathbb{0}_m & \mathbb{0}_m & \cdots & \mathbb{0}_m \\
\end{bmatrix}
\end{align}
\tag{17}
$

### Stationary Mean

The mean is computed from the Moving Average representation and by noting that,

$
\begin{align}
\text{E}(\hat{\mathcal{E}}_t) = 0
\end{align}
\tag{18}
$

It follows that,

$
\begin{align}
\text{E}(\hat{X}_t) = \hat{X}_0\hat{\Phi}^t +  \hat{\mathcal{M}} \frac{\mathbb{1}_m - \hat{\Phi}^t}{\mathbb{1}_m - \hat{\Phi}}
\end{align}
\tag{19}
$

For a stationary solution to be finite it must be that,

$
\begin{align}
\lim_{t\to \infty} \hat{\Phi}^t = 0
\end{align}
\tag{20}
$

To prove this assume that $\hat{\Phi}$ can be diagonalized. Then,

$
\begin{align}
\hat{\Phi} = P \Lambda P^{-1}
\end{align}
\tag{21}
$

where $P$ is the matrix of eigenvectors and $\Lambda$ is a square diagonal matrix of eigenvalues. Consider,

$
\begin{align}
\hat{\Phi}^t &= \left( P \Lambda P^{-1} \right)^t \\
             &= \left( P \Lambda P^{-1} \right)\left( P \Lambda P^{-1} \right)\left( P \Lambda P^{-1} \right)^{t-2} \\
             &= \left( P \Lambda\right)\left(P^{-1}P \right)\left(\Lambda P^{-1} \right)\left( P \Lambda P^{-1} \right)^{t-2} \\
             &= \left( P \Lambda^2 P^{-1} \right)\left( P \Lambda P^{-1} \right)^{t-2} \\
             &= P \Lambda^t P^{-1}
\end{align}
\tag{22}
$

To satisfy stationarity, $\lim_{t\to \infty} \hat{\Phi}^t = 0$, it must be that,

$
\begin{align}
\lim_{t \to \infty} \Lambda^t = 0
\end{align}
\tag{23}
$

which requires that each eigenvalue satisfies, $\lvert \lambda \rvert < 1$. If the eigenvalues of $\hat{\Phi}$ satisfy this condition the stationary mean is given by,

$
\begin{align}
\hat{\mu} = \frac{\hat{\mathcal{M}}}{\mathbb{1}_m - \hat{\Phi}}
\end{align}
\tag{24}
$

### Stationary Covariance Matrix

When computing the covariance matrix simplify things by assuming that $\hat{\mathcal{M}} = 0$. For this case the moving average form of $\text{VAR}(n)$ has the form,

$
\begin{align}
\hat{X}_t = \hat{\Phi}^t \hat{X}_0 + \sum_{i=1}^t \hat{\Phi}^{t-i} \hat{\mathcal{E}}_i
\end{align}
\tag{25}
$

and $\text{VAR}(n)$ becomes,

$
\begin{align}
\hat{X}_t = \hat{\Phi} X_{t-1} + \hat{\mathcal{E}}_t
\end{align}
\tag{26}
$

Let,

$
\begin{align}
\Sigma &= \text{Var}\left[\hat{X}_t\right] \\
       &= \text{E}\left[\hat{X}_t \hat{X}_t^\prime\right] \\
       & = \text{E}\left[\left(\hat{\Phi} X_{t-1} + \hat{\mathcal{E}}_t\right)\left(\hat{\Phi} X_{t-1} + \hat{\mathcal{E}}_t\right)^\prime\right] \\
       & = \text{E}\left[\left(\hat{\Phi} X_{t-1} + \hat{\mathcal{E}}_t\right)\left(X_{t-1}^\prime \hat{\Phi}^\prime  + \hat{\mathcal{E}}^\prime_t\right)\right]
\end{align}
\tag{27}
$

expanding terms gives,

$
\begin{align}
\Sigma = &\text{E}\left[\hat{\Phi}\hat{X}_{t-1}\hat{X}_{t-1}^\prime\hat{\Phi}^\prime\right] + \text{E}\left[\hat{\mathcal{E}}_t\hat{\mathcal{E}}_t^\prime\right] +
         \text{E}\left[\mathcal{E}_t\hat{X}_{t-1}^\prime\hat{\Phi}^\prime\right] + \text{E}\left[\hat{\Phi}\hat{X}_{t-1} \mathcal{E}_t^\prime\right] 
\end{align}
\tag{28}
$

After much simplification it can be shown that,

$
\begin{align}
\Sigma = \hat{\Phi}\Sigma\hat{\Phi}^\prime + \hat{\Omega}
\end{align}
\tag{29}
$

The solution of this equation requires a theorem involving the $\text{vec}$ operator and the Kronecker product. Consider the two matrices $A$ and $B$,

$
\begin{align}
A =
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
\end{align}
\tag{30}
$

$
\begin{align}
B =
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{bmatrix}
\end{align}
\tag{31}
$

the $\text{vec}$ operator is defined by

$
\begin{align}
\text{vec}\left(A\right) &= 
\begin{bmatrix}
a_{11} \\
a_{21} \\
a_{12} \\
a_{22}
\end{bmatrix}
\end{align}
\tag{32}
$

and the Kronecker product, $\otimes$, is defined by

$
\begin{align}
A\otimes B = 
\begin{bmatrix}
a_{11}B & a_{12}B \\
a_{21}B & a_{22}B
\end{bmatrix}
\end{align}
\tag{33}
$

now $a_{11} B$ is given by,

$
\begin{align}
a_{11} B =
\begin{bmatrix}
a_{11} b_{11} & a_{11} b_{12} \\
a_{11} b_{21} & a_{11} b_{22}
\end{bmatrix}
\end{align}
\tag{34}
$

repeating this for all elements gives,

$
\begin{align}
A\otimes B = 
\begin{bmatrix}
a_{11} b_{11} & a_{11} b_{12} & a_{12} b_{11} & a_{12} b_{12} \\
a_{11} b_{21} & a_{11} b_{22} & a_{12} b_{21} & a_{12} b_{22} \\
a_{21} b_{11} & a_{21} b_{12} & a_{22} b_{11} & a_{22} b_{12} \\
a_{21} b_{21} & a_{21} b_{22} & a_{22} b_{21} & a_{22} b_{22} \\
\end{bmatrix}
\end{align}
\tag{35}
$

The theorem needed to solve the problem involves three matrices, $A$, $B$ and $C$, namely,

$
\begin{align}
\text{vec}(ABC) = (C^\prime \otimes A)\text{vec}(B)
\end{align}
\tag{36}
$

Applying this theorem to the expression for the variance gives,

$
\begin{align}
\Sigma &= \hat{\Phi}\Sigma\hat{\Phi}^\prime + \hat{\Omega} \\
\text{vec}\left(\Sigma\right) &= \text{vec}\left(\hat{\Phi}\Sigma\hat{\Phi}^\prime\right) + \text{vec}\left(\hat{\Omega}\right)
\end{align}
\tag{37}
$

Using the theorem on the second term gives the desired result.

$
\begin{align}
\text{vec}\left(\Sigma\right) = \frac{\text{vec}\left(\hat{\Omega}\right)}{\mathbb{1}_n - \hat{\Phi}\otimes\hat{\Phi}}
\end{align}
\tag{38}
$

### Stationary Autocovariance

The autocovariance is defined by,

$
\begin{align}
\Sigma_\tau = \text{E}\left( \hat{X}_t \hat{X}_{t+\tau}^\prime\right)
\end{align}
\tag{39}
$

From the moving average model it can be shown that,

$
\begin{align}
\hat{X}_{t+\tau} &= \hat{\Phi}^\tau \hat{X}_t + \sum_{i=1}^\tau \hat{Phi}^{i-1} \hat{\mathcal{E}}_{t+i} \\
\hat{X}_{t+\tau}^\prime &= \hat{\Phi}^\tau \hat{X}_t + \sum_{i=1}^\tau \hat{Phi}^{i-1} \hat{\mathcal{E}}_{t+i}
\end{align}
\tag{40}
$

It follows that,

$
\begin{align}
\Sigma_\tau &= \text{E}\left( \hat{X}_t \hat{X}_{t+\tau}^\prime \right) \\
&= \text{E}\left( \hat{X}_t \hat{X}_t^\prime \right) \left( \hat{\Phi}^\tau \right)^\prime + \sum_{i=1}^\tau \text{E}\left( \hat{X}_t \hat{\mathcal{E}}_{t+i}\prime \right) \left( \hat{\Phi}^{i-1}\right)^\prime
\end{align}
\tag{41}
$

Recall that,

$
\begin{align}
\text{E}\left( \hat{\mathcal{E}}_{t+i} \right) = 0
\end{align}
\tag{42}
$

and for $i \le t$ and $j \ge 1$,

$
\begin{align}
\text{E}\left( \hat{\mathcal{E}}_i \hat{\mathcal{E}}_{t+j} \right) = 0
\end{align}
\tag{43}
$

Applying these relations to the previous expressions gives the final result,

$
\begin{align}
\Sigma_\tau = \Sigma \left( \hat{\Phi}^\tau \right)^\prime
\end{align}
\tag{44}
$

where $\Sigma$ is the variance from the previous section. This result is reminiscent of the $\text{AR}(1)$ result.   

In [2]:
%reload_ext autoreload
%autoreload 2

# import system modules and set local import path
import os
import sys
import numpy
from matplotlib import pyplot

sys.path.insert(0, os.path.abspath('../../..'))

# import local modules
from lib import config
from lib.data import var

# Config Plot Style
pyplot.style.use(config.glyfish_style)

## Companion Form

### VAR(1), m=2

In [41]:
phi = numpy.array([
        numpy.matrix([[0.75, 0.5],
                      [0.5, 0.75]])])
phi, var.compute_phi_companion_form(phi)

(array([[[0.75, 0.5 ],
         [0.5 , 0.75]]]),
 matrix([[0.75, 0.5 ],
         [0.5 , 0.75]]))

In [4]:
mean =  numpy.array([1.0, 2.0])
mean, var.compute_mean_companion_form(mean, 1)

(array([1., 2.]),
 matrix([[1.],
         [2.]]))

In [12]:
omega = numpy.matrix([[1.0, 0.5],
                      [0.5, 1.0]])
var.compute_omega_companion_form(omega, 1)

matrix([[1. , 0.5],
        [0.5, 1. ]])

### VAR(2), m=3

In [40]:
phi = numpy.array([
        numpy.matrix([[1.0, 0.5, 0.25],
                      [0.5, 1.0, 0.75],
                      [0.5, 0.25, 1.0]]),
        numpy.matrix([[0.25, 0.5, 0.25],
                      [0.5, 0.25, 0.75],
                      [0.5, 0.25,0.25]])])
phi, var.compute_phi_companion_form(phi)

(array([[[1.  , 0.5 , 0.25],
         [0.5 , 1.  , 0.75],
         [0.5 , 0.25, 1.  ]],
 
        [[0.25, 0.5 , 0.25],
         [0.5 , 0.25, 0.75],
         [0.5 , 0.25, 0.25]]]),
 matrix([[1.  , 0.5 , 0.25, 0.25, 0.5 , 0.25],
         [0.5 , 1.  , 0.75, 0.5 , 0.25, 0.75],
         [0.5 , 0.25, 1.  , 0.5 , 0.25, 0.25],
         [1.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
         [0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
         [0.  , 0.  , 1.  , 0.  , 0.  , 0.  ]]))

In [14]:
mean =  numpy.array([1.0, 2.0, 3.0])
mean, var.compute_mean_companion_form(mean, 2)

(array([1., 2., 3.]),
 matrix([[1.],
         [2.],
         [3.],
         [0.],
         [0.],
         [0.]]))

In [17]:
omega = numpy.matrix([[1.0, 0.5, 0.25],
                      [0.5, 1.0, 0.75],
                      [0.5, 0.25, 1.0]])
var.compute_omega_companion_form(omega, 2)

matrix([[1.  , 0.5 , 0.25, 0.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.75, 0.  , 0.  , 0.  ],
        [0.5 , 0.25, 1.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

### VAR(3), m=2

In [39]:
phi = numpy.array([
        numpy.matrix([[0.25, 0.5],
                      [0.5, 0.25]]),
        numpy.matrix([[0.15, 0.35],
                     [0.25, 0.15]]),
        numpy.matrix([[0.05, 0.5],
                     [0.75, 0.1]])
      ])
phi, var.compute_phi_companion_form(phi)

(array([[[0.25, 0.5 ],
         [0.5 , 0.25]],
 
        [[0.15, 0.35],
         [0.25, 0.15]],
 
        [[0.05, 0.5 ],
         [0.75, 0.1 ]]]),
 matrix([[0.25, 0.5 , 0.15, 0.35, 0.05, 0.5 ],
         [0.5 , 0.25, 0.25, 0.15, 0.75, 0.1 ],
         [1.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
         [0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
         [0.  , 0.  , 1.  , 0.  , 0.  , 0.  ],
         [0.  , 0.  , 0.  , 1.  , 0.  , 0.  ]]))

In [21]:
mean =  numpy.array([1.0, 2.0])
mean, var.compute_mean_companion_form(mean, 3)

(array([1., 2.]),
 matrix([[1.],
         [2.],
         [0.],
         [0.],
         [0.],
         [0.]]))

In [22]:
omega = numpy.matrix([[1.0, 0.5],
                      [0.5, 1.0]])
var.compute_omega_companion_form(omega, 3)

matrix([[1. , 0.5, 0. , 0. , 0. , 0. ],
        [0.5, 1. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. ]])

## vec unvec

In [43]:
a = numpy.matrix([[1, 4, 7],
                  [2, 5, 8],
                  [3, 6, 9]])
vec_a = var.compute_vec(a)
vec_a

matrix([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [44]:
var.compute_unvec(vec_a)

matrix([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])

## Stationary Mean, Covariance Matrix and Autocovariance Matrix

### VAR(1)

In [53]:
phi = numpy.array([
        numpy.matrix([[0.75, 0.5],
                      [0.5, 0.75]])])
mean =  numpy.array([1.0, 2.0])
omega = numpy.matrix([[1.0, 0.5],
                      [0.5, 1.0]])

In [58]:
var.compute_mean(phi, mean)

matrix([[4.],
        [0.]])

In [62]:
var.compute_cov(phi, omega)

matrix([[-3.69230769,  4.30769231],
        [ 4.30769231, -3.69230769]])

In [ ]:
var.compute_afc(phi, omega)

matrix([[-3.69230769,  4.30769231],
        [ 4.30769231, -3.69230769]])